const PRODUCT_IMG_MAX_WIDTH = '200px';
const PRODUCT_IMG_MIN_WIDTH = '113px';

export const IMAGE_BLUR_DATA_URL =
  'data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFklEQVR42mN8//HLfwYiAOOoQvoqBABbWyZJf74GZgAAAABJRU5ErkJggg==';

export const PRODUCT_IMG_SIZES = `(min-width: 768px) ${PRODUCT_IMG_MAX_WIDTH}, ${PRODUCT_IMG_MIN_WIDTH}`;
export const RECOMMEND_IMG_SIZES = `(min-width: 360px) ${PRODUCT_IMG_MAX_WIDTH}, ${PRODUCT_IMG_MIN_WIDTH}`;
