name: AWS Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    name: Deploy(Production)
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ./deploy.sh
