name: vercelPreview

on:
  push:
    branches:
      - dev
  delete:
    branches:
      - dev

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ secrets.SOURCE_URL }}
          source_branch: 'dev'
          destination_repo: ${{ secrets.VERCEL_URL }}
          destination_branch: 'dev'
